### ISSUE TITLE
Cannot build with dmd 2.098.1

### ISSUE THREAD

**Issue by nonanonno** [nonanonno/ros2_d#39]
https://github.com/nonanonno/ros2_d/runs/4628352818?check_suite_focus=true#step:4:24

```
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/../../src/phobos/std/container/slist.d(161,28): Error: copy constructor `std.container.slist.SList!(Structure).SList.Node.this(return ref scope inout(Node) p) inout` is not callable using argument types `(typeof(null), Structure)`
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/../../src/phobos/std/container/slist.d(161,28):        cannot pass rvalue argument `null` of type `typeof(null)` to parameter `return ref scope inout(Node) p`
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/../../src/phobos/std/container/slist.d(172,34): Error: template instance `std.container.slist.SList!(Structure).SList.createNodeChain!(Range)` error instantiating
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/../../src/phobos/std/container/slist.d(409,31):        instantiated from here: `insertAfterNode!(Range)`
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/../../src/phobos/std/container/slist.d(198,20):        instantiated from here: `insertFront!(Range)`
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/../../src/phobos/std/container/slist.d(294,21):        instantiated from here: `__ctor!(Range)`
msg_gen/source/msg_gen/parsers/idl.d(85,9):        instantiated from here: `SList!(Structure)`
/tmp/runner/work/_tool/dc/dmd-2.098.1/x64/dmd2/linux/bin64/dmd failed with exit code 1.
dub build :msg_gen : failed
```

- [Change Log of 2.098.1](https://dlang.org/changelog/2.098.1.html)

**Comment by nonanonno** [comment]
Reported on https://issues.dlang.org/show_bug.cgi?id=22619
